# Generated by Django 3.2.7 on 2022-09-21 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_users', to='recipes.Recipe', verbose_name='Не понравившееся рецерты'),
        ),
    ]
