# Generated by Django 3.2.7 on 2022-09-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_customer_dislikes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория блюда', 'verbose_name_plural': 'Категории блюд'},
        ),
        migrations.AddField(
            model_name='customer',
            name='recipes_shown',
            field=models.IntegerField(default=0, verbose_name='Просмотрено рецептов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='subscriber',
            field=models.BooleanField(default=False, verbose_name='Платный подписчик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_users', to='recipes.Recipe', verbose_name='Не понравившиеся рецепты'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='recipes.Recipe', verbose_name='Понравившееся рецепты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Ингредиенты'),
        ),
    ]
