# Generated by Django 3.2.7 on 2022-09-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220925_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='recipes_shown',
            field=models.IntegerField(default=0, verbose_name='Просмотрено рецептов'),
        ),
    ]
