# Generated by Django 3.2.7 on 2022-09-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_customer_recipes_shown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscriber',
            field=models.BooleanField(default=False, verbose_name='Платный подписчик'),
        ),
    ]
