# Generated by Django 3.2.7 on 2022-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instruction',
            field=models.TextField(verbose_name='Инструкция приготовления'),
        ),
    ]
